FROM apache/airflow:2.7.3-python3.9

USER root
# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Switch to airflow user for pip operations
USER airflow
COPY --chown=airflow:root requirements-airflow.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt